### ISSUE TITLE
Domains and apps

### ISSUE THREAD

**Issue by edolnx** [Austin-Devops/austin-devops#5]
I have purchased the following domains for our use:

austin-devops.info
austin-devops.org
austin-devops.com
austin-devops.club
austin-devops.website
austin-devops.services

They are being sponsored by Sphere Cube, and once I have the Sphere Cube panel up we can dole out access accordingly so it's not a SPOF. I'm also willing to host the website through Sphere Cube, and host applications (like a slack replacement) if desired. I would strongly suggest that if we are going to have a website it be on a real domain and not GH Pages simply because things host on GH Pages are not indexed well by search engines.

**Comment by luccacabra** [comment]
Hi @edolnx ! Thanks so much for the contribution, and the offer to host! 

Sooo, the main reason we envision hosting this website on GH pages is so that we don't have to rely on outside funding for website uptime (or any additional application functionality), whether it be from an individual member or a company. ( _This concern would also extend to domain ownership, but as we have a "fallback" URL via GH pages auto-generated URLs, I'm totally 👌with having sponsored domains, so long as all other organizers are too. (:_ )  Additionally, using GH pages keeps all `austin-devops` content in a centralized location, ensures a source of truth for content, and doesn't require any kind of deploy mechanics or maintenance. 

I think that these reasons ☝️ end up outweighing a need for indexing, esp. as we still intend for `meetup.com` to be the main landing page for most user interactions. (i.e. website is intended to be discovered via `meetup.com`)

Anywaaay, that's my view on hosting, but would love to hear other's input!

___

Also, are you looking to have Sphere Cube be an official sponsor via the domain contributions, or is it already an official sponsor? I'm still pretty new to to the group, so I don't know how Sphere Cube currently fits into the organization. :p

**Comment by moutons** [comment]
I'm going to close this one as well as outdated
