### ISSUE TITLE
Determine Required Features For Chat Client

### ISSUE THREAD

**Issue by luccacabra** [Austin-Devops/austin-devops#6]
This issue is meant to serve as a collaboration ground for coming up with a finite list of feature requirements we want/need from a chat client. We'll then use that list to drive our client decision.

### Current List of Requirements
* Ability to create sub-groups within a parent `austin-devops` group
* Free
* Chat history retention

### Ideas/Wants
* Ability to export chat history
* emojis - prooobably not a requirement, but they're really nice to have around to help set the tone of conversations, provide consolidate-able responses (thinking emoji reactions), etc...essentially they make the experience more human

**Comment by luccacabra** [comment]
The first thing I'd like to discuss is whether or not we need infinite chat history. It's definitely a nice feature to have, but is there a really compelling reason to require it? And if there is, is there a compelling reason to need that history in the chat client (instead of exporting it to an indexable outside data store)?

Also, @jjasghar would love for you to post here why your vote is for freenode over other chat clients. I think it'd outline a lot of the things we want from a chat client

**Comment by jjasghar** [comment]
I'm using Freenode as a catch-all for "IRC."

freenode has been around since, [1995](https://en.wikipedia.org/wiki/Freenode) and multiple opensource communities still rely on it day in and day out. It is free and there are multiple free services that can track the history like [botbot.me](https://botbot.me/) that can save our history. 

Slack/Modern collaborative real-time chat clients have come and gone, IRC has been around since the beginning. :)

(IIRC, Slack is actually bulilt upon IRC's frame work, and you can connect via [IRC to Slack](https://get.slack.help/hc/en-us/articles/201727913-Connect-to-Slack-over-IRC-and-XMPP) )

**Comment by moutons** [comment]
closing, as we seem to have been doing well using hangops' #atxdevops as the chatroom of the group for quite some time now. if it comes up again we'll see what happens then, I suppose.
